return {
	ACTIONFAIL =
	{
		STORE =
		{
			NOTALLOWED = "It seems it does not fit.",
		},
	},
	ACTIONFAIL_GENERIC = "I can't do that.",
	ANNOUNCE_ADVENTUREFAIL = "This death will not stop me.",
	ANNOUNCE_BOOMERANG = "I'm so graceful!",
	ANNOUNCE_CHARLIE = "There is someone here in the dark!",
	ANNOUNCE_CHARLIE_ATTACK = "Ouch! Someone is trying to break my bones!",
	ANNOUNCE_COLD = "I am chilled to the bone.",
	ANNOUNCE_HOT = "The bones melting from the heat.",
	ANNOUNCE_CRAFTING_FAIL = "You need to find even a few things to do this.",
	ANNOUNCE_DUSK = "Soon this strange land night falls.",
	ANNOUNCE_EAT =
	{
		GENERIC = "...",
		PAINFUL = "I was right: it's unhealthy food.",
		SPOILED = "I was right: it's unhealthy food.",
		STALE = "I was right: it's unhealthy food.",
		INVALID = "I can't do that.",
		YUCKY = "I was right: it's unhealthy food.",
	},
	ANNOUNCE_ENTER_DARK = "Soon I will not be able seen even my own hands.",
	ANNOUNCE_ENTER_LIGHT = "Again I see that happening.",
	ANNOUNCE_HOUNDS = "It seems the hungry creatures approaching.",
	ANNOUNCE_HUNGRY = "Forces becomes smaller. I'm need to eat.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "I sense the beast's presence nearby",
	ANNOUNCE_HUNT_LOST_TRAIL = "This trail leads nowhere",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "I lost track of the beast.",
	ANNOUNCE_INV_FULL = "I can't carry so much.",
	ANNOUNCE_KNOCKEDOUT = "... My head...",
	ANNOUNCE_NOHUNGERSLEEP = "If I go to sleep now, then I never wake up. First I need to eat.",
	ANNOUNCE_PECKED = "Ouch! It is unpleasant.",
	ANNOUNCE_QUAKE = "I feel as the earth trembles.",
	ANNOUNCE_THORNS = "Ah! They are sharp, you need to act carefully.",
	ANNOUNCE_TORCH_OUT = "The torch had gone out.",
	ANNOUNCE_FAN_OUT = "The blades is damaged, it don't spinning more.",
	ANNOUNCE_COMPASS_OUT = "It seems it will not work more.",
	ANNOUNCE_TRAP_WENT_OFF = "There are so holes in it that even a rabbit can easily out of it.",
	ANNOUNCE_WORMHOLE = "Dune is waiting for me!",
	ANNOUNCE_CANFIX = "I think I can fix it.",
	ANNOUNCE_ACCOMPLISHMENT = "A beautiful cup. But useless.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Why do I even do that?",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "The land is fertile here.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Oh. It was close.",
	ANNOUNCE_BEES = "Bees!",
	ANNOUNCE_DEERCLOPS = "I hear the footsteps of the Horned God!",
	ANNOUNCE_MOSQUITOS = "The bloodsuckers are flying. This pushy and foolish creatures trying to kill me even if I don't have a blood.",
	ANNOUNCE_NODANGERSLEEP = "Too dangerous to sleep now.",
	ANNOUNCE_NODAYSLEEP = "It seems that now is not the time to sleep, it is better to do something useful in good light.",
	ANNOUNCE_NODAYSLEEP_CAVE = "I have a suspicion for some reason that sleep isn't a good idea. Lets call it intuition.",
	ANNOUNCE_NOSLEEPONFIRE = "I'm not going to be burned alive.",
	ANNOUNCE_NODANGERSIESTA = "Too dangerous to sleep now.",
	ANNOUNCE_NONIGHTSIESTA = "The lean-to is not secure enough. The tent would be better.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "The lean-to is not secure enough. The tent would be better.",
	ANNOUNCE_NOHUNGERSIESTA = "I may die from exhaustion in the dream. First you need to find food, and then sleep.",
	ANNOUNCE_SHELTER = "At least some shelter from these streams of water.",
	ANNOUNCE_BURNT = "Um... I'm burning slightly.",
	ANNOUNCE_TOOL_SLIP = "It slip out of my hands...",
	ANNOUNCE_DAMP = "A disgusting slush.",
	ANNOUNCE_WET = "I don't like to be wet, my bones are getting cold.",
	ANNOUNCE_WETTER = "It's too wet!",
	ANNOUNCE_SOAKED = "I need fire or else I'll freeze and shatter into thousands of pieces!",
	BATTLECRY =
	{
		GENERIC = "Death will find you!",
		PIG = "Die, you cowardly beast!",
		PREY = "I will kill you!",
		SPIDER = "Run or die!",
		SPIDER_WARRIOR = "My bones against your fangs!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Maybe I don't much need to kill you?",
	},
	DESCRIBE =
	{
		LLORAR_FLOWER = 
		{ 
			GENERIC ="Llorar's Flower.",
			LONG = "It will be my hope or your hope.",
			MEDIUM = "I can sense a hope's presence growing stronger.",
			SOON = "A hope is almost here!",
			REDY_USE = "A hope is ready to be.",

		},
		GLOMMER = "Friend. It is about as Chester.",
		GLOMMERFLOWER =
		{
			GENERIC = "He grants an ally during the full moon.",
			DEAD = "Life that supported him is faded away.",
		},
		GLOMMERWINGS = "The wonderful wings. It is a pity that they would not serve him any more.",
		GLOMMERFUEL = "It burns perfectly.",
		BELL = "A knell attracts monsters.",
		STATUEGLOMMER =
		{
			GENERIC = "A place of summon.",
			EMPTY = "A lost possibility...",
		},
		WEBBERSKULL = "Oh, it's not my skull. But the skull is of someone interesting.",
		MOLE =
		{
			HELD = "I caught you.",
		},
		MOLEHAT = "It is the eyesight of underground inhabitants that was borrowed.",
		NIGHTSTICK = "A curious weapon. The power of lightning.",
		RABBITHOUSE =
		{
			GENERIC = "Funny architecture.",
			BURNT = "Seems someone lost a house.",
		},
		TURF_DECIDUOUS = "Some soil.",
		TURF_SANDY = "Some soil.",
		TURF_BADLANDS = "Some soil.",
		BEARGER = "The Lord of Forests",
		BEARGER_FUR = "It smells like strength and death",
		FURTUFT = "A piece of the animal.",
		BIGFOOT = "A curious creation, but it is not worth to be caught... under his feet.",
		CACTUS =
		{
			GENERIC = "Barbed.",
			PICKED = "The spikes didn't save him.",
		},
		CACTUS_MEAT_COOKED = "Even I need to eat sometimes.",
		CACTUS_FLOWER = "The thorns protecting something beautiful. Makes sense.",
		COLDFIRE =
		{
			EMBERS = "He needs food to continue cool.",
			GENERIC = "I hope it is cooling the flame will still be useful to me.",
			HIGH = "The fire that cools, not warms. I don't like it.",
			LOW = "This cold flame will go out soon.",
			NORMAL = "The fire that cools, not warms. I don't like it.",
			OUT = "His cold life is over.",
		},
		CATCOON = "A cute critter. I think it has warm fur.",
		CATCOONDEN =
		{
			GENERIC = "It seems someone lives here.",
			EMPTY = "A furry beast lived there, but now it isn't with us.",
		},
		CATCOONHAT = "It's sad in a sense. But it's really warm.",
		COONTAIL = "A tail of the small beast.",
		COOKPOT =
		{
			COOKING_LONG = "It will be ready soon.",
			COOKING_SHORT = "Blub-blub-blub – he says.",
			DONE = "Even I need to eat sometimes.",
			EMPTY = "It is worth thinking about what I can put in there.",
			BURNT = "This is only a frame. It reminds me.",
		},
		EYEBRELLAHAT = "Looks weird, but really helps to deal with the weather.",
		DECIDUOUSTREE =
		{
			POISON = "Forest Degender!",
		},
		ACORN_COOKED = "Even I need to eat sometimes.",
		FARMPLOT =
		{
			GENERIC = "The granting earth.",
			GROWING = "The first sprouts.",
			NEEDSFERTILIZER = "The earth has lost its power. Need to help her.",
		},
		COLDFIREPIT =
		{
			EMBERS = "He needs food to continue cool.",
			GENERIC = "I hope it is cooling the flame will still be useful to me.",
			HIGH = "The fire that cools, not warms. I don't like it.",
			LOW = "This cold flame will go out soon.",
			NORMAL = "The fire that cools, not warms. I don't like it.",
			OUT = "His cold life is over.",
		},
		LIGHTNINGGOAT =
		{
			GENERIC = "It seems to me or it has horns made of copper?",
			CHARGED = "Oh, it sparkles!",
		},
		LIGHTNINGGOATHORN = "This horn gets shocked!",
		MEATRACK =
		{
			DONE = "Everything changes, everything remains unchanged. And this is dried meat.",
			DRYING = "Let it forget about life.",
			GENERIC = "Extends the time... for some things.",
		},
		MERMHEAD =
		{
			GENERIC = "Oh... sorry that it happened.",
		},
		MERMHOUSE =
		{
			GENERIC = "It is unlikely that I would be able to live in this.",
		},
		FLOWERSALAD = "Even I need to eat sometimes.",
		ICECREAM = "Even I need to eat sometimes.",
		WATERMELONICLE = "Even I need to eat sometimes.",
		TRAILMIX = "Even I need to eat sometimes.",
		HOTCHILI = "Even I need to eat sometimes.",
		GUACAMOLE = "Even I need to eat sometimes.",
		MOOSE = "The beast is incongruous, but powerful.",
		MOOSEEGG = "Another strange creature will hatch from it.",
		MOSSLING = "Probably somewhere near their mother?",
		PIGHEAD =
		{
			GENERIC = "Why are these heads hanging here without any meaning?",
		},
		PIGHOUSE =
		{
			FULL = "Dodge-dodge. Craven animal",
			GENERIC = "It is unlikely that I would be able to live in this.",
			LIGHTSOUT = "Dodge-dodge. Craven animal",
			BURNT = "This is only a frame. It reminds me.",
		},
		FERTILIZER = "It helps in the field.",
		RAINOMETER =
		{
			GENERIC = "The weather is generally a problem, but don't known about it - it's a problem yet more.",
			BURNT = "This is only a frame. It reminds me.",
		},
		RAINCOAT = "It protects from getting wet and leaves hands free.",
		RESEARCHLAB =
		{
			GENERIC = "Let's see how useful it is.",
			BURNT = "This is only a frame. It reminds me.",
		},
		RESEARCHLAB2 =
		{
			GENERIC = "Let's see how effective it is.",
			BURNT = "This is only a frame. It reminds me.",
		},
		RESEARCHLAB3 =
		{
			GENERIC = "Who watches the witches?",
			BURNT = "This is only a frame. It reminds me.",
		},
		RESEARCHLAB4 =
		{
			GENERIC = "And then rabbit says: I'm late!",
			BURNT = "This is only a frame. It reminds me.",
		},
		RESURRECTIONSTATUE =
		{
			GENERIC = "Good Old Woo-doo",
			BURNT = "This is only a frame. It reminds me.",
		},
		ICE = "A horribly unpleasant matter.",
		TENT =
		{
			GENERIC = "Sometimes it's better to wait until the darkness is gone.",
		},
		TREASURECHEST =
		{
			GENERIC = "Leave here what is not needed right now.",
		},
		WALL_HAY =
		{
			GENERIC = "It is unlikely that this will stop someone.",
			BURNT = "This is only a frame. It reminds me.",
		},
		WALL_WOOD =
		{
			GENERIC = "So a little better than it does in the open plain.",
			BURNT = "This is only a frame. It reminds me.",
		},
		WATERMELON = "Even I need to eat sometimes.",
		WATERMELON_COOKED = "Even I need to eat sometimes.",
		WINTEROMETER =
		{
			GENERIC = "It can help to understand that winter will be very soon.",
			BURNT = "This is only a frame. It reminds me.",
		},
		HOMESIGN =
		{
			GENERIC = "It says \"you read this inscription\".",
		},
		BEEBOX =
		{
			GENERIC = "One should be careful with it.",
			READY = "It's time to collect tribute.",
			FULLHONEY = "It's time to collect tribute.",
			NOHONEY = "Why do I put a dangerous thing here? Oh yes! Honey!",
			SOMEHONEY = "There is a little bit of honey, but I think you should wait and come back later.",
			BURNT = "This is only a frame. It reminds me.",
		},
		ICESTAFF = "It freezes some troubles.",
		EEL = "Even I need to eat sometimes.",
		EEL_COOKED = "Even I need to eat sometimes.",
		UNAGI = "Even I need to eat sometimes.",
		EYETURRET = "It is ready to kill. I would even say that it likes to do it.",
		EYETURRET_ITEM = "It whispers that he wants to stand on the ground. And to kill someone.",
		MINOTAURHORN = "The power of The Ancient Sentinel.",
		MINOTAURCHEST = "As big as it may contain many amazing things. Or terrible things.",
		THULECITE_PIECES = "Fragments of a powerful material.",
		POND_ALGAE = "The algae.",
		GREENSTAFF = "It is pretty funny thing. This can quickly disassemble almost anything.",
		POTTEDFERN = "A little better to be with it, than quite alone.",
		THULECITE = "The material has absorbed the memory of the Ancients.",
		ARMORRUINS = "The Ancient metal that can protect against knocks",
		RUINS_BAT = "The Ancient metal that can wound seriously.",
		RUINSHAT = "Some things scare even me.",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "All is quiet... as yet.",
			WARN = "The Shadow Cycle begins. They'll be here soon.",
			WAXING = "The glow calls them. The shadows are coming.",
			STEADY = "I'm inside of a nightmare! Amazing. If I survive.",
			WANING = "The activity fizzles. They'll be back in its reality soon.",
			DAWN = "The shadows almost disappeared.",
			NOMAGIC = "The detector of activity this... nightmare story.",
		},
		BISHOP_NIGHTMARE = "It seems the guard has run down. Maybe it is worth to repair it?",
		ROOK_NIGHTMARE = "It seems the guard has run down. Maybe it is worth to repair it?",
		KNIGHT_NIGHTMARE = "It seems the guard has run down. Maybe it is worth to repair it?",
		MINOTAUR = "The result of the irresponsible experiments.",
		SPIDER_DROPPER = "Oh, it is very cute, but biting. This is the same as that on the surface, only it is white rather than black.",
		NIGHTMARELIGHT = "This thing... as if calling the shadows. I have no idea why it was built.",
		RELIC = "A slice of life of ancient. It is worth to look for the materials there.",
		RUINS_RUBBLE = "There's nothing more to take.",
		MULTITOOL_AXE_PICKAXE = "As a Swiss knife.",
		GREENGEM = "The Stone Of Matter.",
		ORANGESTAFF = "Its radiance facilitates the step. Sometimes too.",
		YELLOWAMULET = "Its light fills my bones with strange force...",
		GREENAMULET = "He as if creates matter out of nothing...",
		SLURPER = "It is an always hungry beast. But for all that it is very merry.",
		SLURPER_PELT = "I am pity for this nice beast. But you can make something very useful from its skin.",
		ARMORSLURPER = "In my opinion I'm able not to eat half a year with it.",
		ORANGEAMULET = "It attracts different small things.",
		YELLOWSTAFF = "It commands the heat and the light. This is a striking thing.",
		YELLOWGEM = "The Stone Of Light.",
		ORANGEGEM = "The Stone Of Calm.",
		TELEBASE =
		{
			VALID = "The main is that the troubles weren't in this place.",
			GEMS = "The point of concentration.",
		},
		GEMSOCKET =
		{
			VALID = "The energy is focuses to guide the movement.",
			GEMS = "It will not work without an amethyst.",
		},
		STAFFLIGHT = "Beautiful light.",
		ANCIENT_ALTAR = "It is a fragment of something forgotten that perhaps never was. But it seems as before many useful things can be done with it.",
		ANCIENT_ALTAR_BROKEN = "Hmm. It is not in working condition. Need a thulecite.",
		ANCIENT_STATUE = "It blows from evil. Besides it's a lot of valuable materials.",
		LICHEN = "In my opinion that it's even edible. But hardly useful.",
		CUTLICHEN = "Even I need to eat sometimes.",
		CAVE_BANANA = "Even I need to eat sometimes.",
		CAVE_BANANA_COOKED = "Even I need to eat sometimes.",
		CAVE_BANANA_TREE = "It's funny to find it specifically in a cave.",
		ROCKY = "It is very calm creature.",
		BLUEAMULET = "The bones aching from it",
		PURPLEAMULET = "This is the way to see the true face of this place",
		TELESTAFF = "It helps to leave some troubles behind and meet new.",
		MONKEY = "If you take a million of these and give them typewriters...",
		MONKEYBARREL = "The worth of primitive minds.",
		MONSTERLASAGNA = "It looks as unhealthy food.",
		HOUNDSTOOTH = "Trophy.",
		ARMORSNURTLESHELL = "This shell didn't saved her owner.",
		BAT = "He yelps.",
		BATBAT = "The idea is strange... but what is there not strange?",
		BATWING = "Food? Probably it is not very useful.",
		BATWING_COOKED = "Even I need to eat sometimes.",
		BATCAVE = "This is the cute but noisy creatures' house.",
		BEDROLL_FURRY = "Another's skin will shelter me from the cold and the night.",
		BUNNYMAN = "Underground furry beast.",
		FLOWER_CAVE = "A really useful plant.",
		FLOWER_CAVE_DOUBLE = "A really useful plant.",
		FLOWER_CAVE_TRIPLE = "A really useful plant.",
		GUANO = "Manuring.",
		LANTERN = "Lucifer's thing?",
		LIGHTBULB = "Light of Nature",
		MANRABBIT_TAIL = "Suitable for insulation.",
		MUSHTREE_TALL =
		{
			GENERIC = "It glows nice.",
			BLOOM = "I think it's beautiful.",
		},
		MUSHTREE_MEDIUM =
		{
			GENERIC = "Typically the mushrooms are not this size.",
			BLOOM = "I think it's beautiful.",
		},
		MUSHTREE_SMALL =
		{
			GENERIC = "Typically the mushrooms are not this size.",
			BLOOM = "I think it's beautiful.",
		},
		MUSHTREE_TALL_WEBBED = "They entangled it in order that to save or to outrage?",
		SLURTLE = "Stones-eater.",
		SLURTLE_SHELLPIECES = "Shards of the shell.",
		SLURTLEHAT = "I doubt it will help me more than it did for the original owner.",
		SLURTLEHOLE = "The slow-moving creatures' nest.",
		SLURTLESLIME = "Slime.",
		SNURTLE = "Her armor is very durable.",
		SPIDER_HIDER = "Cute but bites.",
		SPIDER_SPITTER = "Cute, but spits.",
		SPIDERHOLE = "It seems this stone is inhabited.",
		STALAGMITE = "If its split, you can find something valuable.",
		STALAGMITE_FULL = "If its split, you can find something valuable.",
		STALAGMITE_LOW = "If its split, you can find something valuable.",
		STALAGMITE_MED = "If its split, you can find something valuable.",
		STALAGMITE_TALL = "If its split, you can find something valuable.",
		STALAGMITE_TALL_FULL = "If its split, you can find something valuable.",
		STALAGMITE_TALL_LOW = "If its split, you can find something valuable.",
		STALAGMITE_TALL_MED = "If its split, you can find something valuable.",
		TURF_CARPETFLOOR = "Some soil.",
		TURF_CHECKERFLOOR = "Some soil.",
		TURF_DIRT = "Some soil.",
		TURF_FOREST = "Some soil.",
		TURF_GRASS = "Some soil.",
		TURF_MARSH = "Some soil.",
		TURF_ROAD = "Some soil.",
		TURF_ROCKY = "Some soil.",
		TURF_SAVANNA = "Some soil.",
		TURF_WOODFLOOR = "Some soil.",
		TURF_CAVE = "Some soil.",
		TURF_FUNGUS = "Some soil.",
		TURF_SINKHOLE = "Some soil.",
		TURF_UNDERROCK = "Some soil.",
		TURF_MUD = "Some soil.",
		POWCAKE = "Even I need to eat sometimes.",
		CAVE_ENTRANCE = "This obstruction is easy to remove.",
		CAVE_ENTRANCE_RUINS = "This obstruction is easy to remove.",
		CAVE_ENTRANCE_OPEN = "The below should be interesting, but it is necessary to take along at least a torch.",
		CAVE_EXIT = "Time to go back upstairs?",
		BOOMERANG = "A great way hit on the head from myself!",
		MAXWELLPHONOGRAPH = "I know that tune.. fairly grievously, right?",
		PIGGUARD = "It is guarding its seedbeds and torch. A fanatic.",
		ADVENTURE_PORTAL = "Brother of the the Revelation.",
		AMULET = "I can do it without this stuff",
		ANIMAL_TRACK = "Tracks of a big prey.",
		ARMORGRASS = "I hope that something more robust will be found soon.",
		ARMORMARBLE = "Well, bite through it... if you can.",
		ARMORWOOD = "It will allow some time not to die in a battle.",
		ARMOR_SANITY = "It perfectly combines with the color of my eyes",
		ASH =
		{
			GENERIC = "Ashes to ashes.",
			REMAINS_EYE_BONE = "The revelation burnt his eye. But there is surely other in this world.",
		},
		AXE = "The second key to survival.",
		BABYBEEFALO = "Little ball of fur.",
		BACKPACK = "A bit of heaviness will not harm.",
		BACONEGGS = "Even I need to eat sometimes.",
		BANDAGE = "To bandage and to continue.",
		BEARDHAIR = "Stubble.",
		BEDROLL_STRAW = "To fall asleep in the evening, to wake up in the morning... It's tiresome.",
		BEE =
		{
			GENERIC = "Deep down she wants to kill everyone.",
			HELD = "I caught you.",
		},
		BEEFALO =
		{
			GENERIC = "The сhild of The Horned God.",
			NAKED = "You need to wait until the fur grows back.",
			SLEEPING = "Now I can shaving him.",
		},
		BEEFALOHAT = "Hm... Horns",
		BEEFALOWOOL = "The wool of the beast.",
		BEEHAT = "Less bites, more honey?",
		BEEHIVE = "One should be careful with it.",
		BEEMINE = "Why should I fight, if bees want to kill them all in any case?",
		BERRIES = "Berries.",
		BERRIES_COOKED = "Even I need to eat sometimes.",
		BERRYBUSH =
		{
			BARREN = "By itself, it has not yet the strength to grow. Need to help.",
			WITHERED = "The sun and dryness killing as cold and humidity.",
			GENERIC = "Gift of Nature",
			PICKED = "Now Nature has nothing to offer me, need to come later.",
		},
		BIRDCAGE =
		{
			GENERIC = "To restrict the freedom of another creature is... bitter but necessary.",
			OCCUPIED = "It is a rugged land. Perhaps it will be easier for you to survive in the cage.",
			SLEEPING = "Take a rest. You never know what will happen tomorrow.",
		},
		BIRDTRAP = "Each flight will be interrupted.",
		BIRD_EGG = "Even I need to eat sometimes.",
		BIRD_EGG_COOKED = "Even I need to eat sometimes.",
		BISHOP = "The watchdog mechanism.",
		BLOWDART_SLEEP = "Let the enemy lie down and think about his behavior",
		BLOWDART_PIPE = "Throw and forget",
		BLOWDART_FIRE = "And I tell him: Hey! You are burning!",
		BLUEGEM = "Will Gem",
		BOARDS = "From this we can already build something",
		BUGNET = "It will help with those who is slipping away.",
		BUSHHAT = "Now you see me, now I'm a bush.",
		BUTTER = "Butter.",
		BUTTERFLY =
		{
			GENERIC = "Similar to a spark... or a flower.",
			HELD = "I caught you.",
		},
		BUTTERFLYWINGS = "The remains of a butterfly. Still beautiful.",
		CAMPFIRE =
		{
			EMBERS = "The last sparks go out and darkness returns.",
			GENERIC = "Darkness became less and uncertainty became less.",
			HIGH = "It seems it's too hot even for me.",
			LOW = "It lacks food.",
			NORMAL = "It shines and warms. That's enough.",
			OUT = "A respite granted by the flame is over.",
		},
		FIREPIT =
		{
			EMBERS = "Darkness became less and uncertainty became less.",
			GENERIC = "It seems it's too hot even for me.",
			HIGH = "It lacks food.",
			LOW = "It shines and warms. That's enough.",
			NORMAL = "A respite granted by the flame is over.",
		},
		CANE = "It helps to bear my burden",
		CARROT = "It's a carrot.",
		CARROT_COOKED = "Even I need to eat sometimes.",
		CARROT_PLANTED = "Rabbitsc are loving it",
		CARROT_SEEDS = "Seeds of the carrot.",
		CHARCOAL = "Black, like nothing else in the wild.",
		CHESTER = "Friend. Like a dog, but a chest.",
		CHESTER_EYEBONE =
		{
			GENERIC = "It's the eye of Chester.",
			WAITING = "Rest and return",
		},
		COOKEDMEAT = "Even I need to eat sometimes.",
		COOKEDMONSTERMEAT = "It's still looks unhealthy food after cooking.",
		COOKEDSMALLMEAT = "Even I need to eat sometimes.",
		CORN = "The Qeen of Plains",
		CORN_COOKED = "Even I need to eat sometimes.",
		CORN_SEEDS = "The children of Queen Of The Fields.",
		CROW =
		{
			GENERIC = "A bird is color of the night.",
			HELD = "I caught you.",
		},
		CUTGRASS = "So, you can make many different useful things with this.",
		CUTREEDS = "So, you can make many different useful things with this.",
		CUTSTONE = "The base of the architecture",
		DEERCLOPS = "The Horned God is insane in the winter.",
		DEERCLOPS_EYEBALL = "He looks into the cold night eternally.",
		DIRTPILE = "It seems, it's worth a look.",
		DIVININGROD =
		{
			COLD = "The source is distant",
			GENERIC = "It seems it receives the signals.",
			HOT = "Somewhere just a few steps!",
			WARM = "The source is getting closer.",
			WARMER = "It is very close now",
		},
		DIVININGRODBASE =
		{
			GENERIC = "It seems it receives the signals.",
			READY = "It is in its place.",
			UNLOCKED = "Let's see what's next.",
		},
		DRAGONFLY = "Hells Spawn!",
		DRAGONFRUIT = "The Fruit Of The Dragon.",
		DRAGONFRUIT_COOKED = "The Fruit Of The Dragon.",
		DRAGONFRUIT_SEEDS = "The seeds of the Dragon fruit.",
		DRAGONPIE = "Even I need to eat sometimes.",
		DRUMSTICK = "Even I need to eat sometimes.",
		DRUMSTICK_COOKED = "Even I need to eat sometimes.",
		DUG_BERRYBUSH = "This may well rise further, a valuable thing.",
		DUG_GRASS = "This may well rise further, a valuable thing.",
		DUG_MARSH_BUSH = "This may well rise further.",
		DUG_SAPLING = "This may well rise further, a valuable thing.",
		DURIAN = "It is rather seasoning than food.",
		DURIAN_COOKED = "Even I need to eat sometimes.",
		DURIAN_SEEDS = "Seeds of the seasoning.",
		EARMUFFSHAT = "Dead rabbits... it's excellent.",
		EGGPLANT = "Gift of Nature.",
		EGGPLANT_COOKED = "Even I need to eat sometimes.",
		EGGPLANT_SEEDS = "Seeds of the root crop of luck.",
		ACORN = "The nuts of this strange tree can be eaten or to plant.",
		ACORN_SAPLING = "It will grow into a new tree.",
		EVERGREEN =
		{
			BURNING = "It gives light and warmth, but it will not last long.",
			BURNT = "This is only a frame. It reminds me.",
			CHOPPED = "There is nothing to cut.",
			GENERIC = "Not to see the wood for the trees.",
		},
		EYEPLANT = "Plants-hounds.",
		FEATHERHAT = "Beauty requires sacrifice, is not it?",
		FEATHER_CROW = "Feather of a raven, black as coal.",
		FEATHER_ROBIN = "Feather of a red bird, red as berries.",
		FEATHER_ROBIN_WINTER = "Feather of a snow birds, white as snow.",
		FIREFLIES =
		{
			GENERIC = "A tiny lights in the dark.",
			HELD = "The lights in my pocket.",
		},
		FIREHOUND = "Evil fanged creature.",
		FIRESTAFF = "It burns some troubles.",
		FISH = "Raw fish.",
		FISHINGROD = "Someone came out on land already, and someone not...",
		FISH_COOKED = "Even I need to eat sometimes.",
		FLINT = "A primitive tool.",
		FLOWER = "Similar to a spark... or a butterfly.",
		FLOWER_WITHERED = "The sun and dryness killing as cold and humidity.",
		FLOWERHAT = "Laurel or funeral? That is the question.",
		FLOWER_EVIL = "Looks spiteful.",
		FOOTBALLHAT = "It is against shaking my fragile skull.",
		FROG =
		{
			DEAD = "Go back to the earth from which had come.",
			GENERIC = "Annoying creature, you should beware of its tongue.",
			SLEEPING = "Sleeping creature.",
		},
		FROGGLEBUNWICH = "Even I need to eat sometimes.",
		FROGLEGS = "Pieces of the frog.",
		FROGLEGS_COOKED = "Even I need to eat sometimes.",
		GHOST = "It's only a disturbed dead man.",
		GOLDENAXE = "Gold is stronger than a stone. Time to chop.",
		GOLDENPICKAXE = "Gold is stronger than a stone. Time to split.",
		GOLDENSHOVEL = "Gold is stronger than a stone. Time to dig.",
		GOLDNUGGET = "Gold.",
		GRASS =
		{
			BARREN = "In itself it has no forces to rise. Need to help her.",
			WITHERED = "The sun and dryness killing as cold and humidity.",
			BURNING = "A prairie fire is quick and tough.",
			GENERIC = "Grass in the wind is simple as life itself.",
			PICKED = "Your leaves useful elsewhere.",
		},
		GUNPOWDER = "The Black Death",
		HAMBAT = "The idea is strange... but what is there not strange?",
		HAMMER = "An instrument eliminating the unnecessary things.",
		HEALINGSALVE = "To knit the bones.",
		HEATROCK =
		{
			FROZEN = "It needs a fire.",
			COLD = "It needs a fire.",
			GENERIC = "Able to store heat.",
			WARM = "It hardly warms the palms.",
			HOT = "It cools off now instead of me.",
		},
		HONEY = "Sweet... I hate sweet",
		HONEYCOMB = "The remains of the bee house.",
		HORN = "Horn.",
		HOUND = "Fanged creature.",
		ICEBOX = "Sometimes the cold may be friendly.",
		ICEHOUND = "Disgusting cold fanged creature!",
		KILLERBEE =
		{
			GENERIC = "She clearly wants to kill everyone.",
			HELD = "I caught you.",
		},
		KNIGHT = "The watchdog mechanism.",
		KOALEFANT_SUMMER = "Better to kill you in the winter.",
		KRAMPUS = "Demon came to pick up my stuff.",
		KRAMPUS_SACK = "Demon's bag.",
		LEIF = "Forest Degender!",
		LEIF_SPARSE = "Forest Degender!",
		LIGHTNING_ROD =
		{
			CHARGED = "Lightning will serve me for a while.",
			GENERIC = "Better him than me.",
		},
		LIVINGLOG = "The piece of wood has a soul.",
		LOG = "So, you can make many different useful things with this.",
		LUREPLANT = "Plant-predator.",
		MANDRAKE_ACTIVE = "Run behind me is very strange of you.",
		MANDRAKE_PLANTED = "The mighty mandrake. I should pick it at night.",
		MANDRAKE = "Now she would serve me.",
		MARSH_BUSH =
		{
			BURNING = "The spikes do not save from the fire.",
			GENERIC = "This bush ready to fight.",
			PICKED = "Its spikes were no protection.",
		},
		MARSH_PLANT = "A part of Nature.",
		MARSH_TREE =
		{
			BURNING = "Gives light and heat, but it will not last long.",
			BURNT = "This is only a frame. It reminds me.",
			CHOPPED = "However, the spikes are not enough to survive.",
			GENERIC = "Even motionless trying to defend themselves.",
		},
		MAXWELL = "How are you, the prisoner of the Shadow?",
		MEAT = "Raw meat.",
		MERM = "Yeah, ugly fellow.",
		MINERHAT = "It seems that the light pours from my eyes.",
		MONSTERMEAT = "It looks as unhealthy food.",
		MOSQUITO =
		{
			GENERIC = "I have no blood, but he bites unpleasant.",
			HELD = "I caught you.",
		},
		MOSQUITOSACK = "The bag for blood... and it seems with blood.",
		MOUND =
		{
			DUG = "Empty.",
			GENERIC = "To desecrate the graves as it were not well, but... often useful.",
		},
		NIGHTLIGHT = "Burn and let me see them",
		NIGHTMAREFUEL = "What is a sweet little thing, she tries to get in my head",
		NIGHTSWORD = "The weapon that fits me",
		NITRE = "A basis for gunpowder.",
		ONEMANBAND = "Listen and obey!",
		PANFLUTE = "It is one of the tools of the Horned God.",
		PAPYRUS = "For the notes.",
		PERD = "Stupid bird",
		PETALS = "The remains of the flowers. Still beautiful.",
		PICKAXE = "The first key to survival.",
		PIGGYBACK = "They are more useful in death",
		PIGKING = "Well, at least someone live is good.",
		PIGMAN =
		{
			DEAD = "Go back in the earth from which had come.",
			FOLLOWER = "Will be useful to me some time.",
			GENERIC = "Cowardly animals.",
			WEREPIG = "Aggressive and dangerous to society.",
		},
		PIGSKIN = "Pig's skin.",
		PINECONE = "You can get a new tree from this. A valuable thing.",
		PINECONE_SAPLING = "It will grow into a new tree.",
		PITCHFORK = "An instrument subduing a ground.",
		PLANT_NORMAL =
		{
			GENERIC = "Gift of Nature",
			GROWING = "Gift of Nature",
			READY = "Even I need to eat sometimes.",
			WITHERED = "The sun and dryness killing as cold and humidity.",
		},
		POMEGRANATE = "The Fruit Of Hades.",
		POMEGRANATE_COOKED = "The Fruit Of Hades.",
		POMEGRANATE_SEEDS = "The trap for Persephone.",
		POND = "Here may be devils?",
		POOP = "Manuring.",
		PUMPKIN = "Jack's head?",
		PUMPKINCOOKIE = "Even I need to eat sometimes.",
		PUMPKIN_COOKED = "Even I need to eat sometimes.",
		PUMPKIN_LANTERN = "Hi, Jack! Oh, is it just a pumpkin?",
		PUMPKIN_SEEDS = "It is possible to raise the Lamp Jack from this.",
		PURPLEGEM = "Mind Gem",
		RABBIT =
		{
			GENERIC = "A small piece of a meat.",
			HELD = "I caught you.",
		},
		RABBITHOLE =
		{
			GENERIC = "Knock-knock, is anybody home?",
			SPRING = "And now someone can't go in there, and someone can't come out.",
		},
		RAZOR = "To get a bristle of the beast.",
		REDGEM = "Heart Gem",
		REEDS =
		{
			BURNING = "It will burn very quickly.",
			GENERIC = "The basis of Egyptian Civilization.",
			PICKED = "Your leaves useful elsewhere.",
		},
		RUINS_RUBBLE = "I can to do it without this thing.",
		RESURRECTIONSTONE = "But an extra life never hurts.",
		ROBIN =
		{
			GENERIC = "A bird is color of the fire.",
			HELD = "I caught you.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "A bird is color of the ice.",
			HELD = "I caught you.",
		},
		ROCK = "Stone.",
		ROCKS = "Some small rocks",
		ROPE = "To tie knots.",
		SAPLING =
		{
			BURNING = "It will burn very quickly.",
			WITHERED = "The sun and dryness killing as cold and humidity.",
			GENERIC = "Just a part of nature.",
			PICKED = "Your twigs useful elsewhere.",
		},
		SEEDS = "From them you can grow something new.",
		SEEDS_COOKED = "You can't grow anything of them now. But you can eat them.",
		SEWING_KIT = "Needlework always saves in these parts.",
		SHOVEL = "The third key to survival.",
		SILK = "One of the strongest materials in the world.",
		SKELETON = "Hi! Oh, you're dead...",
		SMALLBIRD =
		{
			GENERIC = "Hello there little one",
			HUNGRY = "It seems it is hungry.",
			STARVING = "If you don't feed its right now - he will die.",
		},
		SMALLMEAT = "Raw meat.",
		SPEAR = "The Weapon",
		SPIDER =
		{
			DEAD = "Oh... sorry that it happened.",
			GENERIC = "Cute but bites.",
			SLEEPING = "Probably, will it be better, if not to wake him?",
		},
		SPIDERDEN = "Sweet home charming creatures.",
		SPIDEREGGSACK = "This is an important thing for the spider.",
		SPIDERGLAND = "A poison is the basis of any the medicine.",
		SPIDERHAT = "This will allow you to control spiders for a while.",
		SPIDERQUEEN = "Spiders serve its.",
		SPIDER_WARRIOR =
		{
			DEAD = "Oh... sorry that it happened.",
			GENERIC = "The Defender of the Nest.",
			SLEEPING = "Probably, will it be better, if not to wake him?",
		},
		SPOILED_FOOD = "Manuring.",
		STATUEMAXWELL = "Vile fellow.",
		STINGER = "Trophy.",
		STRAWHAT = "Country style. Dreamed to go on vacation for a long time.",
		SWEATERVEST = "The clothes is not bad",
		TALLBIRD = "Looks very angry.",
		TALLBIRDEGG = "It can be eaten or grown from it... the bird.",
		TALLBIRDEGG_COOKED = "Not bad with bacon.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Now too cold is bad for the eggs.",
			GENERIC = "It seems someone is trying to get out.",
			HOT = "Now too hot is bad for the eggs.",
			LONG = "It only began to grow inside the egg. Waiting for a long time.",
			SHORT = "It seems very soon I will find the miracle of birth.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Hmm. A large egg.",
			PICKED = "The nest is empty.",
		},
		TEENBIRD =
		{
			GENERIC = "My strange pet",
			HUNGRY = "It seems it is hungry.",
			STARVING = "So hungry that he considers me edible!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "The revelation: to leave this place for another... almost the same.",
			GENERIC = "The revelation. Acquaintance me technology.",
			LOCKED = "This mechanism doesn't want to work.",
			PARTIAL = "The revelation is not yet ready. Need a few more parts.",
		},
		TELEPORTATO_BOX = "The third key to the Revelation.",
		TELEPORTATO_CRANK = "The second key to the Revelation.",
		TELEPORTATO_POTATO = "The fourth key to the Revelation.",
		TELEPORTATO_RING = "The first key to the Revelation.",
		TENTACLE = "Dangerous creature.",
		TENTACLESPOTS = "Hm...",
		TENTACLESPIKE = "One of the best trophies.",
		TENTACLE_PILLAR = "It's so big... Of couse, there are things the same as it but smaller near it. You need to be careful.",
		TENTACLE_PILLAR_HOLE = "I'm sure I'm not quite finished with it. It will be back.",
		TENTACLE_PILLAR_ARM = "Do you dream to grow up and kill everyone around?",
		TENTACLE_GARDEN = "It's so big... Of couse, there are things the same as it but smaller near it. You need to be careful.",
		TOPHAT = "Maybe it will turn out  to do something more interesting later",
		TORCH = "The flame is in my hands. Stay away.",
		TRAP = "It's easier than running after them or from them.",
		TRAP_TEETH = "There were stranger teeth become my",
		TRAP_TEETH_MAXWELL = "It seems it can kill me.",
		TRINKET_1 = "Nothing useful, just an item for exchange.",
		TRINKET_2 = "Nothing useful, just an item for exchange.",
		TRINKET_3 = "Nothing useful, just an item for exchange.",
		TRINKET_4 = "Nothing useful, just an item for exchange.",
		TRINKET_5 = "Nothing useful, just an item for exchange.",
		TRINKET_6 = "Nothing useful, just an item for exchange.",
		TRINKET_7 = "Nothing useful, just an item for exchange.",
		TRINKET_8 = "Nothing useful, just an item for exchange.",
		TRINKET_9 = "Nothing useful, just an item for exchange.",
		TRINKET_10 = "Nothing useful, just an item for exchange.",
		TRINKET_11 = "Nothing useful, just an item for exchange.",
		TRINKET_12 = "Nothing useful, just an item for exchange.",
		TRINKET_13 = "Nothing useful, just an item for exchange.",
		TRINKET_14 = "Nothing useful, just an item for exchange.",
		TRINKET_15 = "Nothing useful, just an item for exchange.",
		TRINKET_16 = "Nothing useful, just an item for exchange.",
		TRINKET_17 = "Nothing useful, just an item for exchange.",
		TRINKET_18 = "Nothing useful, just an item for exchange.",
		TRINKET_19 = "Nothing useful, just an item for exchange.",
		TRINKET_20 = "Nothing useful, just an item for exchange.",
		TRINKET_21 = "Nothing useful, just an item for exchange.",
		TRINKET_22 = "Nothing useful, just an item for exchange.",
		TRINKET_23 = "Nothing useful, just an item for exchange.",
		TRINKET_24 = "Nothing useful, just an item for exchange.",
		TRINKET_25 = "Nothing useful, just an item for exchange.",
		TRINKET_26 = "Nothing useful, just an item for exchange.",
		TRINKET_27 = "Nothing useful, just an item for exchange.",
		TRUNKVEST_SUMMER = "It looks useful",
		TRUNKVEST_WINTER = "This is really a useful thing",
		TRUNK_COOKED = "Even I need to eat sometimes.",
		TRUNK_SUMMER = "The remains of a strong animal.",
		TWIGS = "So, you can make many different useful things with this.",
		UMBRELLA = "I'd rather be dry than wet.",
		WALL_HAY_ITEM = "Their defensive value is questionable",
		WALL_STONE = "So a better than it does in the open plain.",
		WALL_STONE_ITEM = "Barrier.",
		WALL_RUINS = "Solid as a bigoted belief.",
		WALL_RUINS_ITEM = "This will help protect from the material enemies.",
		WALL_WOOD_ITEM = "There is some semblance of obstacle.",
		WASPHIVE = "One should be VERY careful with it.",
		WINTERHAT = "This is a really useful thing",
		WORMHOLE =
		{
			GENERIC = "Probably, I may need some help of Atreides to open it?",
			OPEN = "Shai-Hulud?",
		},
	},
	DESCRIBE_TOODARK = "I can't see anything. Very uncomfortable.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Just right now this life for me is more useful as a food, not a squeaky ball of feathers.",
	},
}